### ISSUE TITLE
P110 getting current energy usage via different api method 

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [mihai-dinculescu/tapo#109]
I'm seeking help in adding support in p110 api to get current power draw, let me explain.

All my "smart" devices are on network without internet access for privacy and security concerns and i've noticed that if the device turns on and connects to that network or even looses connection and then reconnects, none of the `get_device_usage`,`get_energy_usage`,`get_energy_usage` work which in the tplink app i can see as no energy usage graphs whatsoever. To fix that you need to kickstart them with internet connection and then they work fine just fine. But while they are not working, i noticed in the app i could still see current power draw and fankly thats all i care about (on/off works fine), so i was hoping you could help me/we could work together on finding out that api method, but if you got P110/115 then you don't need my help :P

I'm happy to provide any information and help in any way i can to get it as it's stopping me from achieving perfection

**Comment by Michal-Szczepaniak** [comment]
So far i tested the `get_current_power` and indeed, `get_device_usage`/`get_energy_usage`/`get_energy_data` all fail with different unknown tapo errors and `get_current_power` does indeed return current power draw!

**Comment by Michal-Szczepaniak** [comment]
Imma close this now since it's merged and I was able to do it myself :P

**Comment by mihai-dinculescu** [comment]
It's been released in [v0.7.2](https://github.com/mihai-dinculescu/tapo/releases/tag/v0.7.2). Thank you!

**Comment by mihai-dinculescu** [comment]
I'm all for adding whatever it's helpful to people.

What do you have in mind?

**Comment by Michal-Szczepaniak** [comment]
While looking at the apps code i just noticed some other functions, might not be exactly useful but full api coverage would be good no?

+ i'm gonna add small thingy to generate mappings for c++ which i used for my project

**Comment by mihai-dinculescu** [comment]
I don't think that full API coverage should be a target in itself because:
- the API is private, and Tp-Link might pull the plug on it or revamp it any day
- there is no documentation, and some of the endpoints, especially the ones that change the state of the device, are quite time-consuming to figure out how they work

However, if someone needs a particular function, I'll gladly support its addition.

If you're looking into adding FFI-related stuff, you might want to look at and/or branch off https://github.com/mihai-dinculescu/tapo/pull/100.

**Comment by Michal-Szczepaniak** [comment]
Oki gotcha that makes sense

Hmm but thats for python gotta add bindings for c++ along with cbindgen :P But well this is not issue for that

Thanks

**Comment by effizientest** [comment]
> I've done a bit of reverse engineering on the app (i'm newb) and i've located `CurrentPowerResult` which returns ONLY `currentPower` which I strongly believe is the result i'm interested in, and the request is called `get_current_power`

I'm getting 
```
DEBUG:tapo.api.api_client:Get Current power...
DEBUG:tapo.api.protocol.klap_protocol:Request: {"method":"get_current_power","params":null}
DEBUG:tapo.api.protocol.klap_protocol:Device responded with: TapoResponse { error_code: 0, result: Some(CurrentPowerResult { current_power: 0 }) }
```
get_energy_usage() works...

**Comment by Michal-Szczepaniak** [comment]
perhaps current power draw is 0? I've not had issues with it ever since, and get_enery_usage just returned inbuilt statistics

**Comment by effizientest** [comment]
yes, thanks absolutely feasible
DEBUG:tapo.api.api_client:Get Current power...
DEBUG:tapo.api.protocol.klap_protocol:Request: {"method":"get_current_power","params":null}
DEBUG:tapo.api.protocol.klap_protocol:Device responded with: TapoResponse { error_code: 0, result: Some(CurrentPowerResult { current_power: 98 }) }
***Current power: {'current_power': 98}

So my next problem is how to install on RPi?

**Comment by Michal-Szczepaniak** [comment]
I think that's incorrect place to ask :)
