### ISSUE TITLE
How to actually use this?

### ISSUE THREAD

**Issue by rdvansloten** [mihai-dinculescu/tapo#113]
I have no idea how to use this Python code and the README and examples don't make this clear. Import tapo, but import from what? I tried renaming tapo.pyi, but this just throws errors about the classes like PlugHandler being undefined. Could you explain how this Python code should actually be used? It would be nice to have a step-by-step in the README.

Copy/pasting the Python examples and running it doesn't work.

**Comment by mihai-dinculescu** [comment]
The Python wrapper is WIP and it needs a bit more work before it can be used. I should have made this more obvious in the readme, sorry for confusing you.

**Comment by mihai-dinculescu** [comment]
@rdvansloten version v0.1.1 of the Python library has been released.
The README.md has been updated with information on how to use it.

Please let me know how you find it :)
