### ISSUE TITLE
Python support/examples for L530 please

### ISSUE THREAD

**Issue by hydnum-repandum** [mihai-dinculescu/tapo#123]
I've just joined the github community to congratulate mihai-dinculescu for the great tapo package.  Unfortunately i don't know rast, but i am at home with python.  Please add python support for lights, in particular the l530 light bulb.  Thank you very very much.  8)

**Comment by mihai-dinculescu** [comment]
Thank you. It makes me happy to hear that people find this project useful.
Adding support for L530 bulbs in Python is on the roadmap, and it should come in the next several weeks.

**Comment by wandergeek** [comment]
@mihai-dinculescu seconding this one! I'd love to use the python integration for an art installation I'm working on! Would happily tag you in the documentation I make for it. :D

**Comment by mihai-dinculescu** [comment]
As per the commit above, the version on master now has support for the L530, L630, and L900 devices.
Support for the `.set` API will come at a later date.

Feedback will be appreciated.

**Comment by mihai-dinculescu** [comment]
Released in [Tapo Python v0.2.0](https://github.com/mihai-dinculescu/tapo/releases/tag/py-v0.2.0).

**Comment by hydnum-repandum** [comment]
Dear mihai-dinculescu

I am sorry i did not reply sooner.  Thank you for completing the development for L530.  I will be testing your v0.2.0 and will get back to you.

You are a star!  Thank you
