### ISSUE TITLE
H100 Support in Python

### ISSUE THREAD

**Issue by LMT1337** [mihai-dinculescu/tapo#128]
Hi,

are there any plans to support the H100 hub in python? I can see the hub, but I'd like to get data from a temperature sensor thats connected to the hub.

Thanks

**Comment by mihai-dinculescu** [comment]
The plan is to have the Python version on version parity with the Rust one. Support for H100 in Python will come in the next couple of months.

**Comment by mihai-dinculescu** [comment]
I'm currently working on this.

**Comment by mihai-dinculescu** [comment]
Added partial support for the H100 hub and its child devices. Currently, only the `get_device_info` function is supported for the child devices through the hub's `get_child_device_list` method.

**Comment by mihai-dinculescu** [comment]
Closing this as H100 is now fully supported in the Python wrapper.
