### ISSUE TITLE
Issue on Rust

### ISSUE THREAD

**Issue by DangersTR** [mihai-dinculescu/tapo#145]
Hello.
I try to run your Rust projects. But i have a problem about that.  First, I go to ..\tapo-main\tapo-main\tapo folder for build 'Cargo.toml'. 

![image](https://github.com/mihai-dinculescu/tapo/assets/72423325/d07501b4-8a43-480e-8b03-92ac53142caf)

Building succesfully happen. After the build, I run the 'cargo run" command and I get this error.

![image](https://github.com/mihai-dinculescu/tapo/assets/72423325/ca5c36cc-e56c-4636-959a-597644a4c4c2)

I installed the openssl by the way.

**Comment by mihai-dinculescu** [comment]
Please have a look at the [README](https://github.com/mihai-dinculescu/tapo/blob/main/README.md#examples). It explains how individual examples can be run.
