### ISSUE TITLE
ImportError: cannot import name 'ApiClient' from partially initialized module 'tapo' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by vihatsoft** [mihai-dinculescu/tapo#165]
Install pip module with `pip install tapo`

Get error when run python file `python /home/admin/tapo.py`
`ImportError: cannot import name 'ApiClient' from partially initialized module 'tapo' (most likely due to a circular import) (/home/admin/tapo.py)
`

**tapo.py**

```
import asyncio
from tapo import ApiClient

async def main():
    client = ApiClient("xxxxx@gmail.com", "xxxx")
    device = await client.l530("192.168.x.xx")

    await device.off()
    
asyncio.run(main())

**Comment by mihai-dinculescu** [comment]
What Python version are you using?

**Comment by vihatsoft** [comment]
> What Python version and OS are you using?

python 3.9.2

**Comment by mihai-dinculescu** [comment]
[Tapo Python v0.2.0](https://github.com/mihai-dinculescu/tapo/releases/tag/py-v0.2.0) should be working.
Please give it a try.

**Comment by vihatsoft** [comment]
> [Tapo Python v0.2.0](https://github.com/mihai-dinculescu/tapo/releases/tag/py-v0.2.0) should be working. Please give it a try.

Yes Now working fine. 
 toggleOnOff available?

**Comment by mihai-dinculescu** [comment]
There is an [example](https://github.com/mihai-dinculescu/tapo/blob/main/tapo-py/examples/tapo_generic_device_toggle.py) available that shows how the toggle behaviour can be achieved.
