### ISSUE TITLE
Tapo: SessionTimeout

### ISSUE THREAD

**Issue by paha77** [mihai-dinculescu/tapo#180]
I have a P100 smart plug which is connected to the network and active.  When I try to control it get the following error:

```
Tapo: SessionTimeout
```

What does it exactly mean and how could it be avoided?

Thank you.

**Comment by mihai-dinculescu** [comment]
At which point in the code are you getting this error?

**Comment by paha77** [comment]
> At which point in the code are you getting this error?

I've not dug into the code, just using the self-compiled binary in a docker container.

**Comment by mihai-dinculescu** [comment]
This error is returned when the device responds with either Unauthorized (401) or Forbidden (403).
It would be helpful to see your code and to know on which operation that it fail with this error.
