### ISSUE TITLE
P300 support

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [mihai-dinculescu/tapo#184]
Hi, I haven't seen on the list of supported devices any power bar and since i'm thinking of buying one from tapo so that i don't have to implement yet another api i was thinking if it would be possible to add support for it?

From my previous contribution, once i have the device i don't see any issue in adding missing features (i imagine it will need metod for turning each slot on/off and maybe getting statistics per slot other than that it will probably inherit much of plug stuff), but I was wondering if there's maybe something you know of that would prevent me from adding support for them?

If you see no obstacles feel free to respond and close the issue and I'll be back with PR!

**Comment by mihai-dinculescu** [comment]
It should be trivial to implement if it's closer to the P1XX series. 
It might be more challenging if it's closer to the Kasa series, but I hope it's still possible.

The P300 seems to be an EU-only model. I have a KP303 power strip myself that seems to be UK-only.

What Model, Hardware Version and Firmware Version do you get in the Tapo app?

**Comment by Michal-Szczepaniak** [comment]
I don't have the hardware yet, just making sure there are no obvious obstacles, since there are not i'll get the hardware later this or next month and will have all the answers, thanks!

**Comment by Michal-Szczepaniak** [comment]
Added support in #192
