### ISSUE TITLE
[info] How can i use this in a windows C# Application. 

### ISSUE THREAD

**Issue by rawatsaurabh** [mihai-dinculescu/tapo#194]
Hello , 
This is not an issue , but a request for info.
Is it possible to send the command to the tapo bulb over wifi from a C# application ? What modifications i have to do. .Please suggest.

**Comment by mihai-dinculescu** [comment]
It is possible, but it is quite an involved process.
You would have to call Rust code from C# using FFI. See https://github.com/Cysharp/csbindgen/
