### ISSUE TITLE
Is it mandatory to use the Hub? 

### ISSUE THREAD

**Issue by rawatsaurabh** [mihai-dinculescu/tapo#197]
Hello , 
Is it mandatory to use the hub? Can we directly use it with the RGB Bulb ( [Tapo 530L](https://www.amazon.in/TP-Link-Tapo-Compatible-Colour-Changeable-L530B/dp/B08M697H9J?th=1)).

**Comment by mihai-dinculescu** [comment]
It depends on the device.
As mentioned in the product description, L530 does not require a hub.
