### ISSUE TITLE
H100 initialization attempt returns error

### ISSUE THREAD

**Issue by nathanja** [mihai-dinculescu/tapo#203]
Just saw that H100 just got supported - exciting! But when I played with it (in python), I got the following
`AttributeError:` 'builtins.ApiClient' object has no attribute 'h100'. Did you mean: 'p100'?`

I'm not a developer so I'm not sure how to fix the issue.

**Comment by mihai-dinculescu** [comment]
Which version are you using?
The H100 support has been added only to the main branch. It hasn't been released as a published version just yet.

**Comment by nathanja** [comment]
Ah that's probably why, I've been using pip. I'll pull down from source directly shortly and let you know if I still have the issue.

p.s. just in case I have trouble, when would you expect the next version to be published?

**Comment by mihai-dinculescu** [comment]
There are a few other changes I want to add before releasing.
It shouldn't be longer than a week or two.

**Comment by nathanja** [comment]
Managed to get it working from source - thanks!
