### ISSUE TITLE
Example for doing things with devices accessed throung the hub

### ISSUE THREAD

**Issue by mcatkins** [mihai-dinculescu/tapo#213]
It would be nice to have an example of how to access devices behind an h100 hub. In particular I am interested in how to get button events from an S200B and/or temperature/humidity history from a T310.

Comes to think of it, how do we respond in Python to events originating in the device - such as movements detected by the T100?

Great piece of work - many thanks!

**Comment by mihai-dinculescu** [comment]
This functionality exists in the Rust library, and I'm currently porting it to Python.
The effort is tracked in #128.
