### ISSUE TITLE
Local access to TAPO P110 for energy data

### ISSUE THREAD

**Issue by goofy2k** [mihai-dinculescu/tapo#215]
Is acquisition of energy data of the P110 still possible with local access?

I did that succesfully in NodeRed using the staus node of [this flow](https://flows.nodered.org/node/node-red-contrib-tplink-tapo-connect-api).  Lately I get invalid results. Could this be due to blocking of the functionality in recent firmware updates?

**Comment by goofy2k** [comment]
Thanks for your reply!

I have been able to access the devices locally with a Nodered flow.  Currently I can only get the data by using the Export function in the Android Tapo app. This generates a csv file that is sent to my email.

Currently I have no way to get my data available via Homey Pro.

Fred

**Comment by mihai-dinculescu** [comment]
Yes, you can access the device, get device info, turn it on/off, etc, without the device having an internet connection. But to get energy data, it does need an internet connection.

**Comment by goofy2k** [comment]
I will send you a link to the relevant source code(s) later.

Unfortunately I am not able to test it anymore e.g. by switching off my internet connection.

I The API info was allegedly supplied by TP-link. I now suspect that they removed that mode of access in later firmware updates.

Now I have to press a key in the Android app. Then I get an email with the data in some longer period.

I could live with it if I could let a Homey app do that key press all was it in a weekly frequency....

**Comment by goofy2k** [comment]
I discovered that more people hit on this issue. Local access was possible, but the method does not work after a firmware upgrade of the plugs.

You can find the discussion by following the link to the nodered software in my first message. Then follow the link to the relevant github repository and see Issues.

There is a solution available for Home Assistant. It is based on [this](https://github.com/petretiandrea/plugp100/blob/main/plugp100/protocol/klap_protocol.py).

I will test that solution in Python to see if it works for me....

**Comment by mihai-dinculescu** [comment]
Is this the issue that you're referring to?
https://github.com/sanlike0911/node-red-contrib-tplink-tapo-connect-api/issues/38

**Comment by goofy2k** [comment]
Yep

**Comment by mihai-dinculescu** [comment]
That thread is about last year's firmware version that started using the KLAP encryption protocol.
This library does support it.

**Comment by goofy2k** [comment]
OK that's great! I will see if I can get data from my P110's !
I'll have to study how to use the lib

**Comment by mihai-dinculescu** [comment]
It is primarily local access. Most operations do not require the device to be connected to the Internet. However, some, like getting energy usage historical data, do require a cloud connection. Also, the devices need to connect to the cloud from time to time so that the locally cached password hash is synced.
