### ISSUE TITLE
cannot import 'LightHander' or 'ColorLightHandler' for typings

### ISSUE THREAD

**Issue by alfadormx** [mihai-dinculescu/tapo#218]
Hello, 

First of all, thank @mihai-dinculescu for your work in this library.
So, while all we need is to import the ApiClient to use this library, I am trying to add Type support for intellisense in VSCode so I am importing:
```
from tapo import ApiClient, LightHandler, ColorLightHandler
```
and my editor now looks like this:
![image](https://github.com/mihai-dinculescu/tapo/assets/5934048/95844b37-5497-474c-a675-3e9b81bebcc7)

However, this happens when I run the code:
![image](https://github.com/mihai-dinculescu/tapo/assets/5934048/4dcc3a31-aa3f-4e8b-aed0-18e180c01d62)

This is the list of all my imports, I hope this issue isn't related to shadowing or something. 

```
import asyncio
import colorsys
import sys
import TouchPortalAPI as TP
import yaml
from functools import wraps
from typing import Awaitable, Dict, Optional, Tuple, TypeVar, Union
from argparse import ArgumentParser
from TouchPortalAPI.logger import Logger
from tapo import ApiClient, LightHandler, ColorLightHandler
```

So my questions is, were LightHandler and ColorLightHandler not intented to be imported like this? If so, how to import them?
Thank you kindly for your help pointing me into the right direction.

**Comment by mihai-dinculescu** [comment]
They were supposed to be exported.
I've just merged a fix to main.

Thank you for reporting this issue!

**Comment by alfadormx** [comment]
Thank you for fixing this issue. Has this push to main fixed the package dependency? I mean, to take advantage of this fix, shall I only reinstall the dependency with pip?
