### ISSUE TITLE
ApiClient on AWS Lambda

### ISSUE THREAD

**Issue by LucaLovagnini** [mihai-dinculescu/tapo#227]
I'm trying to run the `tapo_p100.py` example on an AWS Lambda (the local version works with my account and device) with the following code:

```
"""P100 & P105 Example"""

import asyncio

from tapo import ApiClient

async def test_device():
    tapo_username = "myusername@email.com"
    tapo_password = "mypassword"
    ip_address = "192.168.1.8"

    client = ApiClient(tapo_username, tapo_password)
    device = await client.p100(ip_address)

    print("Turning device on...")
    await device.on()

    print("Waiting 2 seconds...")
    await asyncio.sleep(2)

    print("Turning device off...")
    await device.off()

    device_info = await device.get_device_info()
    print(f"Device info: {device_info.to_dict()}")

    device_usage = await device.get_device_usage()
    print(f"Device usage: {device_usage.to_dict()}")


def lambda_handler(event, context):
    asyncio.run(test_device())

```

However it fails due to tiemout:
```

{
  "errorMessage": "Http(Error { kind: Timeout, context: None, source: Some(Error { description: \"Timeout was reached\", code: 28, extra: None }), source_type: Some(\"curl::error::Error\"), local_addr: None, remote_addr: None })",
  "errorType": "Exception",
  "requestId": "1a7c8ec3-f4a6-44b8-a1f7-3d34f5ac2963",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 37, in lambda_handler\n    asyncio.run(test_device())\n",
    "  File \"/var/lang/lib/python3.12/asyncio/runners.py\", line 194, in run\n    return runner.run(main)\n",
    "  File \"/var/lang/lib/python3.12/asyncio/runners.py\", line 118, in run\n    return self._loop.run_until_complete(task)\n",
    "  File \"/var/lang/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n",
    "  File \"/var/task/lambda_function.py\", line 14, in test_device\n    device = await client.p100(ip_address)\n"
  ]
}
```

Again, this works correctly if ran (with a classic main) on my computer.

**Comment by mihai-dinculescu** [comment]
This library is designed to work best over the local network.

It looks like you have provided an IP address on your local private network, as you should. However, by default, Lambda cannot access this device on your local private network.

There are ways to get around this, but they are either insecure (opening the device to the internet) or quite involved (VPNs).
Are you sure that cloud is the best choice for your project? This kind of projects usually sit best on a Raspberry Pi that's on the same local private network.

**Comment by KillerJulian** [comment]
Hello, thank you very much for creating this library.

I am running into the same problem. The device (P110) is in a different network. Unfortunately, I cannot access the device directly. In the Tapo mobile phone app I have the possibility to call up the current power consumption. What kind of extension to this library is necessary to be able to access the devices externally? Knowing how to do this?

Kind regards
Julian

**Comment by KillerJulian** [comment]
That makes sense, of course. I have tried to get the Tapo Api documentation, but found nothing on the internet about the cloud interface. For fun, I wrote to tapo support personally, but only an inappropriate answer came back:

> Hello Mr Julian,
> Thank you for recognising our platform.
>
> Here are some points we need to confirm before we forward your case to our sales department for further co-operation.
> 1. copyright If you want further integration of Tapo/Kasa into your automation system, we hope you can provide us with more details about the specific requirements and commercial prospects of the integration.
> 2. copyright If you need the API documentation or want to test the Tapo/Kasa Open API, you need to sign an NDA (non-disclosure agreement) with us.
> After we have evaluated and confirmed that there are cooperation opportunities with your company, we can provide you with a relevant test environment to support you in testing.
> 3. copyright If we have the possibility of formal cooperation, we need to sign a commercial agreement to settle the relevant matters, including integration costs.
>
> We look forward to your feedback.
>
> If you agree with the above points, please leave your official contact information, we will forward your case to the lead engineer for further evaluation.
