### ISSUE TITLE
ImportError: cannot import name 'ApiClient' from partially initialized module 'tapo' (most likely due to a circular import)

### ISSUE THREAD

**Issue by syco** [mihai-dinculescu/tapo#229]
Hi,

I've seen [https://github.com/mihai-dinculescu/tapo/issues/165](https://github.com/mihai-dinculescu/tapo/issues/165) and I tried versions 0.2.0, 0.2.1, and 0.3.0.
They all have this same problem for me.
I'm using ArchLinux, with python 3.12.3

Thanks

**Comment by thkaw** [comment]
> Hi,
> 
> I've seen #165 and I tried versions 0.2.0, 0.2.1, and 0.3.0. They all have this same problem for me. I'm using ArchLinux, with python 3.12.3
> 
> Thanks

I'm encouter similar problem, and I found it cause by my mistake...
I create a tapo.py in same directory that confuse _from tapo import ApiClient_

**Comment by syco** [comment]
That's it.. just don't name your script tapo.py
Thanks
