### ISSUE TITLE
Tapo: SessionTimeout

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [mihai-dinculescu/tapo#235]
Hi I'm randomly getting `Tapo: SessionTimeout` errors when creating `p110` object and I don't know how to fix it

**Comment by mihai-dinculescu** [comment]
What hardware version is the device?

**Comment by Michal-Szczepaniak** [comment]
Application says 1.0

**Comment by mihai-dinculescu** [comment]
Sorry for taking so long to reply.
Is this still an issue?
Does it happen all the time?
Are you using the Rust or Python version?

**Comment by Michal-Szczepaniak** [comment]
I'm using Rust version, compiled as a library for my c++ software (cause i thought rewriting it in c++ is too much work lmao)

It seems to happen only when i'm running two instances of my software so like two softwares asking the light/plug for status at the same time

**Comment by mihai-dinculescu** [comment]
Interesting. Are there any variables shared between the two, or do they run as individual processes?
The SessionTimeout error is a bit misleading. It's more like an invalid session error.

**Comment by Michal-Szczepaniak** [comment]
Its the same code i just have one running "production" 24/7 and one in development

**Comment by mihai-dinculescu** [comment]
I was wondering if the two instances share the same memory (e.g. by running in the same process on different threads, with the handlers created from the same API client instance).
From your last message, it sounds like they aren't sharing any memory.

**Comment by Michal-Szczepaniak** [comment]
nope

**Comment by mihai-dinculescu** [comment]
The good news is that I was able to reproduce the issue by trying to talk with the same P110 device from two different machines.
The bad news is that I'm not sure what could be done in the library to avoid this issue.
All I can do is to recommend to plan for failure and add retry logic in case you want to support this use case.

**Comment by Michal-Szczepaniak** [comment]
yeah i think its fair, it could be firmware issue?

**Comment by mihai-dinculescu** [comment]
It's hard to say for certain, but it could be that the device can maintain only one session at a time...

**Comment by Michal-Szczepaniak** [comment]
yeah since probably only one app is supposed to manage it but eh, it doesn't really matter as i have only one app running 99% of the time

anyway thanks for effort :P
