### ISSUE TITLE
tapo-py :- 0.3.1 getting error while calling get_device_info

### ISSUE THREAD

**Issue by amiyamandal-dev** [mihai-dinculescu/tapo#248]
### Description
When trying to fetch device information using `get_device_info()` for a P110 device, the following error occurs:

```python
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[18], line 1
----> 1 device_info = await device.get_device_info()
Exception: Serde(Error("missing field `overheated`", line: 1, column: 832))
```

### Environment
- Python version: 3.11
- Tapo-py version: 0.3.1

### Steps to Reproduce
1. Create a device object for P110
2. Call `await device.get_device_info()`

### Expected Behavior
The function should return the device information without any errors.

![image](https://github.com/user-attachments/assets/f05e9f1d-bdf1-415e-bcb4-871fc9adf226)

**Comment by mihai-dinculescu** [comment]
Can you please post the output of `get_device_info_json()`?

**Comment by btab** [comment]
Here's a (redacted) dump from my p110. Looks like they helpfully renamed `overheated` to `overheat_status`. So I'd suggest changing the field name and adding a serde alias for the old name (for people on old firmware). Additionally, I'm guessing it's part of the change that introduced `overcurrent_status` and `power_protection_status`.

```json
{"auto_off_remain_time":0,"auto_off_status":"off","avatar":"house","charging_status":"normal","default_states":{"state":{"on":false},"type":"custom"},"device_id":"REDACTED","device_on":true,"fw_id":"00000000000000000000000000000000","fw_ver":"1.3.1 Build 240621 Rel.162048","has_set_location_info":true,"hw_id":"REDACTED","hw_ver":"1.0","ip":"REDACTED","lang":"en_US","latitude":0,"longitude":-0"mac":"REDACTED","model":"P110","nickname":"REDACTED","oem_id":"REDACTED","on_time":0,"overcurrent_status":"normal","overheat_status":"normal","power_protection_status":"normal","region":"REDACTED","rssi":0,"signal_level":2,"specs":"","ssid":"REDACTED","time_diff":0,"type":"SMART.TAPOPLUG"}
```

**Comment by Dav-v** [comment]
Hi all, same issue on my Tapo P115, firmware version `1.3.1 Build 240621 Rel.162048` . I confirm that there is not `overheated` field anymore but only `'overheat_status': 'normal'`

**Comment by Toommi** [comment]
I have the same issue with P110 -- is there a work around or do we need to wait for a new version?

**Comment by sledgemhammer** [comment]
same here 
`
Traceback (most recent call last):
  File "C:\Program Files (x86)\Domoticz\tapo_p110.py", line 74, in <module>
    asyncio.run(main())
  File "C:\Program Files (x86)\Python310-32\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files (x86)\Python310-32\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Program Files (x86)\Domoticz\tapo_p110.py", line 40, in main
    device_info = await device.get_device_info()
Exception: Serde(Error("missing field `overheated`", line: 1, column: 832))
`

**Comment by smiklosovic** [comment]
same here!

**Comment by padenot** [comment]
Fixed in https://github.com/mihai-dinculescu/tapo/pull/254, verified to work on my P110 and P115.

**Comment by mihai-dinculescu** [comment]
I was able to find out the following by decompiling a recent Tapo Android app

Possible values for the overheat_status are
- cool_down
- normal
- overheated

This change seems to affect only plugs (and possibly power strips, but I couldn't test it as I don't have one).

Therefore, I believe that only the plugs should be updated for now to support the new enum.

**Comment by sledgemhammer** [comment]
@mihai-dinculescu Can i buy you one to support your future development ?

**Comment by mihai-dinculescu** [comment]
@sledgemhammer [Sponsorship](https://github.com/sponsors/mihai-dinculescu) is enabled for the project. Every little bit helps <3

The fix has been released in [Tapo Rust v.0.7.13](https://github.com/mihai-dinculescu/tapo/releases/tag/v0.7.13) and [Tapo Python v0.3.2](https://github.com/mihai-dinculescu/tapo/releases/tag/py-v0.3.2).
The overheated field for plugs has been replaced by three enums: `overcurrent_status`, `overheat_status`, and `power_protection_status`.
Please let me know how this works for you.
