### ISSUE TITLE
LED Strip turns off briefly before custom static lighting effect

### ISSUE THREAD

**Issue by ThibaultHP** [mihai-dinculescu/tapo#260]
Hello,

I’m trying to create a system that mimics Ambilight by lighting up my LED strip according to a color sequence I define based on the colors that appear on the edges of my screen (my LED strip is mounted behind my desk). The code works, but every time I set a new effect (via `device.set_lighting_effect`), the LED strip briefly turns off before displaying my sequence correctly, which is not desirable. I want the strip to transition from one color sequence to another without turning off between sequences.

Do you have any ideas on how I could solve this issue? Thank you.

**Comment by mihai-dinculescu** [comment]
Given that the Tapo API exhibits the same behavior, there’s probably not much we can do about it. The library itself isn’t causing the delay; it might just take some time to compute the schedule.
