### ISSUE TITLE
EnergyUsageResult.today_energy wrong units in comments?

### ISSUE THREAD

**Issue by felixwatts** [mihai-dinculescu/tapo#262]
The comments say this field (and several similar ones) are in watts, but watts isn't a unit of energy. Should it be kilowatt hours or maybe Joules?

**Comment by mihai-dinculescu** [comment]
It's Watts per hour. That's what the Tapo API returns.
You can divide the value by 1000 to get Killowats per hour.

It would be good to have the documentation updated.

**Comment by mjp4** [comment]
It will be "Watt Hours" (i.e. Power * time), not Watts per Hour (which would be Power / Time, which doesn't make sense).

**Comment by mihai-dinculescu** [comment]
@felixwatts, @mjp4, could you please review the referenced PR to verify that the correct units are now specified?
