### ISSUE TITLE
Question: how about compatibility of P110 firmware versions with your Python module versions?

### ISSUE THREAD

**Issue by goofy2k** [mihai-dinculescu/tapo#282]
After losing control of my P110 plugs due to a firmware update, I started using your module under Python successfully. To prevent further disappointments I switched off automatic firmware updates.  I am also hesitant to start using new releases of your module. But I am curious for recent improvements as I see a lot of activity on your repo!

With this respect I have some questions:
- Where can I find the relevant version number(s) of the tapo module that I use?
- My current P110 firmware version is 1.3.0 Build 230905 Rel. 152200
- The Tapo app tells me that v 1.3.1 Build 240621 Rel. 162048 is available  
- Do you have a table or other overview showing mutual compatibility of your module versions with P110 firmware versions?

Thanks, Fred

**Comment by mihai-dinculescu** [comment]
I aim to keep the library up-to-date with the latest firmware versions.
Of course, there is always the risk that a new firmware version will break something and that it might take me (or the community) a few days to deliver a fix.
To help with this, I keep on automatic firmware updates for my devices.

I can confirm that the latest version of the library works well with 1.3.1 Build 240621 Rel. 162048.
As for what version of the Python library you have, this should get it for you

**Comment by goofy2k** [comment]
OK, that is clear! Thanks

I have to think of a strategy to update my application.



Op vr 18 okt 2024 19:56 schreef Mihai Dinculescu ***@***.***>:
