### ISSUE TITLE
Exception at code:  device = await client.p110(ip)

### ISSUE THREAD

**Issue by goofy2k** [mihai-dinculescu/tapo#288]
I use the Python module to acquire data from my P110 smart plug.  My overall application is rather forgiving for e.g. failed connections. But I keep track of (rare) exceptions to see iimprove my application step by step.

At a line containing device = await client.p110(ip) I **now and then** got:  ```Exception: Tapo(Unknown(1003)). ```  

At the same line of code I now get:

```
Exception: Http(reqwest::Error { kind: Request, url: "http://192.168.2.15/app", source: hyper_util::client::legacy::Error(Connect, ConnectError("tcp connect error", Os { code: 113, kind: HostUnreachable, message: "No route to host" })) })
```  

Between both occurrences I successfully switched from version 0.3.0 of the module to version 0.5.1 . I wonder if both events in fact have the same root cause.  So: is it just a matter of a change in the exception message?

**Comment by goofy2k** [comment]
Tiny detail: please note the typo in the description of the error:   "reqwest"  should be "request" ;-)

**Comment by mihai-dinculescu** [comment]
The `HostUnreachable` error is self-explanatory: the network connection between the plug and the device trying to call it has been lost. `reqwest::Error` is the type of error. It comes from the rust crate called `reqwest`, and that's why it shows up like that.

The `1003` error is slightly different, as it's an actual error returned by the plug, and I don't think it has much to do with the other one.

Are you getting it on login exclusively? What's the frequency? Are there any patterns that you can notice?

**Comment by goofy2k** [comment]
Thanks. Do I understand you well, that these are two separate errors that
still could occur after my update?

I got the reqwest error only one time now. The other error occurred tens of
times (once a day, over say 100 calls). I do not have exact data yet.

When the error occurs, my current app just exits and restarts after an
hour. I may want to implement a try/except algorithm to do several tries
within a single hourly call.

But I find that less usefull if e.g. the error is caused by instability of
my WIFI network. As mentioned: my application is forgiving for missing data
of hourly calls as it collects daily data.

Op ma 28 okt 2024 22:37 schreef Mihai Dinculescu ***@***.***>:

**Comment by mihai-dinculescu** [comment]
Yeah, you're correct.

I'm not too worried about `HostUnreachable`. I'm pretty confident that it's a networking issue that has nothing to do with the library or your code.

But if you manage to find a way to replicate the random `1003` error that you're getting, I would be very interested in figuring out if it can be avoided or if it can become a better-documented error.

By the way, version v0.6.0 supports end-to-end logging.

```python
import logging
logging.basicConfig(level=5)
```

The above will give the most detailed logs, while `logging.basicConfig(level=logging.DEBUG)` and `logging.basicConfig(level=logging.INFO)` and so no less.

**Comment by goofy2k** [comment]
OK. I will go to v0.6.0 and see what I can do with the logging option!

Fred

Op di 29 okt 2024 21:16 schreef Mihai Dinculescu ***@***.***>:

**Comment by goofy2k** [comment]
Updated to V0.6.0.
Implemented logging in "production" app. Currently running with DEGUG level logs.
Timestamped logs are being saved to file.
Waiting for next occurrences of the errors. In version 0.3.0 / 0.5.1 they occurred about once every 2 - 3 days, at 24 (48?) calls a day.
Now building more reliable statistics....

**Comment by goofy2k** [comment]
Have been using improved logging and v0.6.0 in "production" (Linux, Synology NAS, Python 3.8.15) since 2024-10-30 16:41.
Doing 2 acquisitions  with get_energy_data and EnergyDataInterval.Daily  every day just after midnight.
No runtime errors detected yet but period is relatively short.

Further improving logging with logging.info ongoing to get more info in case the error occurs. 

Keep you posted when an event was detected either in "production" (Linux, Synology NAS, Python 3.8.15)  or "dev" (Win32, PC, Visual Studio 2022, Python 3.11.8)

Unfortunately I can not  mathch the Python versions on Linux and Win32.

**Comment by goofy2k** [comment]
For the first time since 28/10 the runtime error occurred! Normally these errors occurred more often. Note that starting from 30/10 I use V0.6.0 of your tapo lib. I enclose the error mesage which now also contains debug information. Probably the error can be caused by a glitch in my Wifi network (please add your comment about that).  I also include the relevant lines of my Python code.  If stability of the network could be the cause, a solution would probably be to test for success in the async def connectDevice routine and do retries for a limited period of time? (please comment on this) 

My current code:
```
async def connectDevice(client,ip):
    #isolated this code to implement catching errors later
    device = await client.p110(ip)      #line 43
    return device

    #define client
    tapo_username = secrets.get("TAPO_USERNAME")
    tapo_password = secrets.get("TAPO_PASSWORD")
    client = ApiClient(tapo_username, tapo_password)   # must test success / catch error
    #define devices
    Boiler_IP = secrets.get("BOILER_IP")
    Elga_Ace_IP = secrets.get("WARMTEPOMP_IP")
    Elga_Ace_MAC = secrets.get("WARMTEPOMP_MAC")
    logging.info(f"tapo module version {version('tapo')}")
    logging.info(f"connect client to TAPO device for Elga Ace")
    device = await connectDevice(client,Elga_Ace_IP)                    #line 62
```

The error message:    (Exception 20241115 _10-00-03.txt)
INFO lines are generated by my application
DEBUG lines come from the tapo module
```
DS718plus - Synology DiskStation
10:00 (33 minuten geleden)
aan mij

Taakplanner heeft een geplande taak voltooid.

Taak: 3. taskManager released
Starttijd: Fri, 15 Nov 2024 10:00:01 +0100
Stoptijd: Fri, 15 Nov 2024 10:00:06 +0100
Huidige status: 1 (Onderbroken)
Standaard output/fout:
2024-11-15 10:00:03,046 - DEBUG - Using selector: EpollSelector
2024-11-15 10:00:03,052 - INFO - tapo module version 0.6.0
2024-11-15 10:00:03,053 - INFO - connect client to TAPO device for Elga Ace
2024-11-15 10:00:03,054 - DEBUG - Device url: http://<local_ip>/app
2024-11-15 10:00:03,055 - DEBUG - Testing the Passthrough protocol...
2024-11-15 10:00:03,055 - DEBUG - Component negotiation request: {"method":"component_nego","params":null}
2024-11-15 10:00:03,055 - DEBUG - starting new connection: http://<local_ip>/
2024-11-15 10:00:06,061 - DEBUG - Supported. Setting up the Passthrough protocol...
2024-11-15 10:00:06,061 - DEBUG - Generating RSA key pair...
2024-11-15 10:00:06,120 - DEBUG - Performing handshake...
2024-11-15 10:00:06,121 - DEBUG - starting new connection: http://<local_ip>/
Traceback (most recent call last):
  File "/volume1/admin_data/taskManager/taskManager.py", line 506, in <module>
    taskObjList = execute_objTasks(taskObjList)
  File "/volume1/admin_data/taskManager/taskManager.py", line 152, in execute_objTasks
    task.execute()
  File "/volume1/admin_data/taskManager/Task.py", line 146, in execute
    result = getTAPOforElgaLogs.task(['energy_daily']) 
  File "/volume1/admin_data/taskManager/getTAPOforElgaLogs.py", line 259, in task
    result = asyncio.run(getLogs(request_info))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/volume1/admin_data/taskManager/getTAPOforElgaLogs.py", line 62, in getLogs
    device = await connectDevice(client,Elga_Ace_IP)
  File "/volume1/admin_data/taskManager/getTAPOforElgaLogs.py", line 43, in connectDevice
    device = await client.p110(ip)
Exception: Tapo(InvalidResponse)


Van DS718plus
```

**Comment by mihai-dinculescu** [comment]
Thank you, this is very helpful.
Can you please post a log of what a successful connection looks like? 
I'm surprised that your plugs still use the Passthrough protocol. Is the firmware up to date?

**Comment by mihai-dinculescu** [comment]
Closing this issue as the above PR should resolve it. Please feel free to reopen if it does not.
