### ISSUE TITLE
Same start and end time  tapo 110

### ISSUE THREAD

**Issue by effizientest** [mihai-dinculescu/tapo#293]
The start and endtime is identical for daily and monthly data:

Smarte Steckdose 
***Energy data (hourly): {'data': [0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0], 'end_timestamp': 1730674799, 'interval': 60, 'local_time': '2024-11-03T18:42:25', 'start_timestamp': 1730588400}
***Energy data (daily): {'data': [88, 9, 8, 277, 9, 9, 107, 8, 9, 9, 9, 8, 9, 96, 8, 9, 47, 140, 4, 0, 170, 9, 41, 90, 9, 0, 0, 165, 6, 77, 89, 8, 9, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'end_timestamp': **1727733600**, 'interval': 1440, 'local_time': '2024-11-03T18:42:25', 'start_timestamp': **1727733600**}
***Energy data (monthly): {'data': [2067, 331, 0, 0, 0, 1690, 1953, 827, 1471, 1519, 24, 0], 'end_timestamp': **1704063600**, 'interval': 43200, 'local_time': '2024-11-03T18:42:25', 'start_timestamp': **1704063600**}

**Comment by mihai-dinculescu** [comment]
This has been discussed in https://github.com/mihai-dinculescu/tapo/issues/221, and the caveats mentioned there are present in the API documentation.
I appreciate that it's not the best or most obvious behaviour, so I will look into ways to improve it.

**Comment by effizientest** [comment]
Many thanks, so we will ignore the end. Another questions relates to the units used. Is there a site mentioning units (interval=sec?)?
Many thanks

**Comment by mihai-dinculescu** [comment]
The returned `interval` should be in minutes, per the [documentation](https://github.com/mihai-dinculescu/tapo/blob/main/tapo/src/responses/energy_data_result.rs#L26).
