### ISSUE TITLE
Can you provide me with API information?

### ISSUE THREAD

**Issue by parkkh12** [mihai-dinculescu/tapo#295]
Hello, I want to control the P110 with ESP32. However, I'm blocked at the login step when accessing the HTTP. In which file can I find the related code?

**Comment by mihai-dinculescu** [comment]
You probably want to start with https://github.com/mihai-dinculescu/tapo/blob/main/tapo/src/api/protocol/klap_protocol.rs.

**Comment by ZeChArtiahSaher** [comment]
is there a possibility or an existing api that would interface with tapo via bluetooth as well to bypass tp link cloud entirely?

**Comment by mihai-dinculescu** [comment]
This library requires local network access either via WiFi or LAN.
