### ISSUE TITLE
P300 on/off support

### ISSUE THREAD

**Issue by tarceri** [mihai-dinculescu/tapo#303]
Curious why the on/off support is missing. Is it just that the required requests are not yet known/documented? 

petretiandrea seems to have it working now in his home assistant app https://github.com/petretiandrea/home-assistant-tapo-p100/issues/336 so I guess the key to support is there somewhere in https://github.com/petretiandrea/plugp100 ?

**Comment by mihai-dinculescu** [comment]
On/off support is provided for the individual plugs rather than the power strip itself.
Have you seen the [available example](https://github.com/mihai-dinculescu/tapo/blob/main/tapo-py/examples/tapo_p300.py)?
