### ISSUE TITLE
Raspberry OS

### ISSUE THREAD

**Issue by effizientest** [mihai-dinculescu/tapo#304]
Hello, great undertaking, do you have some tips for Rpi?
Looking in indexes pypi.org/simple piwheels.org/project/scipy
could not install packages due to an environment error  404 client error piwheels.org/project/scipy/tapo

**Comment by effizientest** [comment]
Yes but where it is told to search there?  and I already told not to use the cache. May be I can try wget.

**Comment by effizientest** [comment]
What a mess- tried to upgrade to wayland - tapo installed but not the GUI...

**Comment by mihai-dinculescu** [comment]
I'm still not quite sure what the specific issue is or if it pertains to this library.

I'll close this issue for now. However, feel free to reopen it if you require support with this library. Please include details about what you're attempting to do and the problems you're facing.

**Comment by effizientest** [comment]
very old distro version  led to a selection of the wrong file, not my fault
