### ISSUE TITLE
L900 Function Is Missing From Python 0.7.0 Version

### ISSUE THREAD

**Issue by dabiggestclown** [mihai-dinculescu/tapo#307]
Tried to install python library, specified in my requirements.txt
```
tapo==0.7.0
```

![image](https://github.com/user-attachments/assets/3ddaa8eb-2e4f-491f-bc9a-ef5ab3c362c4)

Looked into ApiClient, it is missing l900 function. Maybe l900 changes has not pushed to pypi.org?

**Comment by mihai-dinculescu** [comment]
You are correct.
L900 support is currently only on `main` and is planned for v0.8.0 (alongside L920 and L930).

Until the release happens, you can install the package straight from the git main branch as a workaround.

**Comment by dabiggestclown** [comment]
I tried to install it with pip install -r requirements.txt
`tapo @ git+https://github.com/mihai-dinculescu/tapo.git`

It throws this error, I assume because pyproject.toml is not in the root folder.
```
does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```
