### ISSUE TITLE
How to trigger the alarm/chime on H100

### ISSUE THREAD

**Issue by ankitseal** [mihai-dinculescu/tapo#310]
Hi,
I tried to look through the code but I can't find a clear way to identify and trigger the inbuilt chime in the Tapo H100. Can someone please point me towards how I can achieve it? Thanks

**Comment by rytilahti** [comment]
The `get_support_alarm_type_list` return a list of tunes supported by the device, this is an example from a H100: `{"get_support_alarm_type_list": {"alarm_type_list": ["Doorbell Ring 1", "Doorbell Ring 2", "Doorbell Ring 3", "Doorbell Ring 4", "Doorbell Ring 5", "Doorbell Ring 6", "Doorbell Ring 7", 
"Doorbell Ring 8", "Doorbell Ring 9", "Doorbell Ring 10", "Phone Ring", "Alarm 1", "Alarm 2", "Alarm 3", "Alarm 4", "Dripping Tap", "Alarm 5", "Connection 1", "Connection 2"]}}`

You may also find https://github.com/python-kasa/python-kasa/blob/master/kasa/smart/modules/alarm.py a useful reference. Thanks @mihai-dinculescu for pointing out that the `play_alarm` supports parameter overrides :-)

**Comment by ankitseal** [comment]
Thanks for your reply. I am not well versed in Rust but can try to figure it out. Can I get access to the decompiled API? is it available as a Postman collection?

**Comment by mihai-dinculescu** [comment]
This feature is now supported on `main` and will be included in the next release, thanks to @kay.
