### ISSUE TITLE
P110 regression introduced in 7.13

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [mihai-dinculescu/tapo#324]
Hi, sorry it took so long for me to catch it.

In 7.13 you added 
```
To align with the latest API updates, the overheated field for plugs has been replaced by three enums: overcurrent_status, overheat_status, and power_protection_status (thanks to @padenot).
```

P300 doesn't seem to have them

```Serde: missing field `overcurrent_status` at line 1 column 726```

**Comment by mihai-dinculescu** [comment]
Ah, this is annoying, but it's not the end of the world.
I was planning to separate the P300 implementation from the P304, as the latter comes with energy monitoring.

Can you please post the `device_info_json` result for P300?

**Comment by Michal-Szczepaniak** [comment]
Don't know about the "first issue" :D

Also there has been mistake in my assumption. P300 is not at fault, its actually P110

```{"auto_off_remain_time":0,"auto_off_status":"off","avatar":"plug","default_states":{"state":{},"type":"last_states"},"device_id":"device_on":true,"fw_id":"fw_ver":"1.2.3 Build 230425 Rel.142542","has_set_location_info":false,"hw_id":"hw_ver":"1.0","ip":"","lang":"en_US","latitude":0,"longitude":0,"mac":","model":"P110","nickname":"oem_id":"on_time":13221422,"overheated":false,"power_protection_status":"normal","region":"","rssi":-45,"signal_level":3,"specs":"","ssid":"","time_diff":60,"type":"SMART.TAPOPLUG"}```

**Comment by mihai-dinculescu** [comment]
AFAIK `1.3.1 Build 240621 Rel.162048` is the latest fw version for P110 HW v1 plugs.
Are you able to update to it?

**Comment by Michal-Szczepaniak** [comment]
I mean, they're working fine and I wasn't planning on updating them… ever, but if there's no other way then i either stay on old version or update?

**Comment by mihai-dinculescu** [comment]
You can either stick with the current firmware version and an older version of Tapo that supports it or upgrade the firmware to use the latest version of Tapo.

For what it's worth, I have several plugs around the house running the latest versions, and they work fine. I'm pretty good at staying on top of the breaking changes.

**Comment by Michal-Szczepaniak** [comment]
>I'm pretty good at keeping up with the breaking changes.

Why then introduce breaking change in a patch xd That should be major :P

**Comment by mihai-dinculescu** [comment]
Sorry about that. I'm adhering to the model where any release before version 1.0 can potentially include breaking changes.
