### ISSUE TITLE
basic guide of usage under windows?

### ISSUE THREAD

**Issue by stylemessiah** [mihai-dinculescu/tapo#45]
Assume most people have no idea how to set this up under say windows, a guide would be very handy

All we see is a mention of installing SSL under windows....and i can do that and have been doing that since the days of squid port (squidnt) for windows :) its everything else i have no clue about :)

edit:/update:

tried to get there on my own and as usual what looks simple given the README of a github repo, its anything and ive gone around in circles for the last 3 hours, and arrived right back where i started

what ive tried....

downloading:

rust-1.65.0-i686-pc-windows-gnu.msi (1st time rust user - cant say im a fan given the dependency hell under windows)
as advised by rust page:
msys2-x86_64-20221028.exe
ran msys2 setup (ive used msys2 before)
then ran pacman -S mingw-w64-ucrt-x86_64-gcc for build env

used set to set variables for IP,username.password

and then (as advised when trying to run) cargo run --example tapo_p110

i ran:

pacman -S openssl-devel pkg-config

which completed fine, but cargo still complained turning on backtracing showed it was complaining that openssl couldnt be found, but it was installed fine...

after an hour of getting nowhere i came across an alternate solution that involved installing the alternate msvc version of rust and 9.79Gb of Microsoft Visual Studio, at which point with my connection i tapped out and gave up.

there has to be a less torturous and data download hungry way to do this under windows, surely its just sending json payloads???

i really wish when people put up code they actually put a guide for people to actually use it - have a look at the instructions on my AutoBan PHP code for Unifi Gateways on my repo and the code commentary, thats documentation...

https://github.com/stylemessiah/Unifi-Auto-Ban

**Comment by mihai-dinculescu** [comment]
@stylemessiah it looks like rustc is struggling to locate it, even though you might have installed it correctly.

Have you checked that the `OPENSSL_DIR` env variable is set in the shell you are trying to run the example in?

**Comment by felixhauptmann** [comment]
I'm building with `stable-x86_64-pc-windows-msvc` on windows. Installing ssl via vcpkg (as described under [troubleshooting](https://github.com/mihai-dinculescu/tapo#troubleshooting)) was sufficient.
