### ISSUE TITLE
Using as logstash producer

### ISSUE THREAD

**Issue by nine-2-five** [mihai-dinculescu/tapo#89]
Hi,

I made some changes (mainly added a loop) to Mihai's code and dockerized it, but after a period of time the output to console stops while the process is still running, the docker container still exists.

Can anyone more knowledgeable in Rust take a look at this loop and see what's wrong with it?

https://github.com/nine-2-five/tapo-logstash-source/blob/master/examples/tapo_p110.rs

**Comment by mihai-dinculescu** [comment]
There isn't anything wrong with the code.
I would have suspected that the Tapo session expires after a fashion, but that should give errors.

Can you tell after how long it stops outputting?

Also, this filters out any output not coming from a component (your executable or one of its libraries) that doesn't contain `tapo` in its name. Your executable's info message won't appear if it's called `logtash`. You might want to change or remove the filter.

```rust
    pretty_env_logger::formatted_timed_builder()
        .filter(Some("tapo"), log_level)
        .init();
```
